
export const MODULOS_KEY='MODULOS_KEY'

export const PERMISOS_KEY='PERMISOS_KEY'


export const Public_KEY='PUBLIC_KEY'


export const TIPO_USUARIO_KEY='TIPO_USUARIO_KEY'


export const PUBLIC_INTERNO_KEY='PUBLIC_INTERNO_KEY'