export enum PermisosE {
  
    ASIGNAR_STOCK = "ASIGNAR STOCK",
    CANCELAR_TRANSFERENCIAS = "CANCELAR_TRANSFERENCIAS",
    ELIMINAR_TRANSFERENCIAS = "ELIMINAR",
    REALIZAR_TRANSFERENCIAS = "REALIZAR_TRANSFERENCIAS",
    RECIBIR_TRANSFERENCIAS = "RECIBIR_TRANSFERENCIAS",
    ACEPTAR_TRANSFERENCIAS = "ACEPTAR",
    RECHAZAR_TRANSFERENCIAS = "RECHAZAR",
  

  


    TIPO_SUCURSAL_USUARIOS = "TIPO_SUCURSAL",
    TIPO_AREA_USUARIOS = "TIPO_AREA",
    TIPO_NINGUNO_USUARIOS = "TIPO_NIGUNO",

    LISTAR_STOCK_SUCURSAL = "LISTAR"
  }

  
  export enum permisosCrudE {
    LISTAR='LISTAR',
    EDITAR='EDITAR',
    ELIMINAR='ELIMINAR',
    CREAR='CREAR'
}