export enum PermisoE {
  LISTAR = "LISTAR",
  EDITAR = "EDITAR",
  ELIMINAR = "ELIMINAR",
  CREAR = "CREAR",
  ASIGNAR_STOCK = "ASIGNAR STOCK",
  CANCELAR_TRANSFERENCIAS = "CANCELAR_TRANSFERENCIAS",
  REALIZAR_TRANSFERENCIAS = "REALIZAR TRANSFERENCIAS",
  RECIBIR_TRANSFERENCIAS = "RECIBIR TRANSFERENCIAS",
  APROBAR = "APROBAR",
  RECHAZAR = "RECHAZAR",
  LISTAR_ROL = "LISTAR ROL",
  LISTAR_USUARIOS = "LISTAR USUARIOS",
  TIPO_SUCURSAL = "TIPO SUCURSAL",
  TIPO_AREA = "TIPO AREA",
  TIPO_NINGUNO = "TIPO NIGUNO"
}