export enum estadoE {
    PENDIENTE = 'PENDIENTE',
    APROBADO = 'APROBADO',
    RECHAZADO = 'RECHAZADO',
    CANCELADO = 'CANCELADO',
    REENVIADO = 'REENVIADO',
    RECHAZO_ACEPTADO = 'RECHAZO ACEPTADO', 
}
